---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '9090'
    - --scheme
    - http
    image: docker.1ms.run/semitechnologies/weaviate:1.28.2
    ports:
    - 9090:9090
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
...